### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PengLx** [VoChiDanh/SoulPoints#6]
**Describe the bug**
This lastes vesion can not enable correct 

**Logs**
[[Paste errors logs to pastebin.com](https://paste.ubuntu.com/p/FZjTRRfZhH/)](https://paste.ubuntu.com/p/cHxMYXZQJ7/)

**Server Version**
1.18 paper
**Plugins Version**
[v1.3.7 Build 1]

**Screenshots**

**Comment by VoChiDanh** [comment]
Try this jar https://github.com/VoChiDanh/SoulPoints/releases/download/v1.3.x/SoulPoints.jar

**Comment by PengLx** [comment]
> Try this jar https://github.com/VoChiDanh/SoulPoints/releases/download/v1.3.x/SoulPoints.jar

It works

**Comment by VoChiDanh** [comment]
> > Try this jar https://github.com/VoChiDanh/SoulPoints/releases/download/v1.3.x/SoulPoints.jar
> 
> It works
thanks for report, if you don't have anything error or bug we can close this ?

**Comment by PengLx** [comment]
> > > Try this jar https://github.com/VoChiDanh/SoulPoints/releases/download/v1.3.x/SoulPoints.jar
> > 
> > 
> > It works
> 
> thanks for report, if you don't have anything error or bug we can close this ?

yeah of course
