### ISSUE TITLE
[Suggest] add Blacklist world

### ISSUE THREAD

**Issue by PengLx** [VoChiDanh/SoulPoints#8]
**Clearly describe your new request feature.**
World Blacklist
I see the config and there is a option world to enable this plugin
But If you know there are some dungeon plugins spawn a world for a dungeon and it name was random
And I want to Let the SoulPoints enalbe in that world is too hard
So I hope the world whitelist can be blacklist

**Comment by VoChiDanh** [comment]
I'll replace whitelist world to blacklist world :thinking:

**Comment by VoChiDanh** [comment]
download build 3 and change 
`available-world` to `disable-world` in config
